# Site settings
title: Mark Nyon
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://trystant.github.co" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Mark Nyon
user_description: I'm a Software Engineer and Educator. Lately I have been immersed in <b>education</b> working for 2U. I work on Education based applications. Visit my blog <a href="https://blog.grandkru.com" target="_blank">here</a>.
user_title: Software Engineer
email: nyonmark@gmail.com
twitter_username: scorintha
github_username:  trystant
linkedin_username: marknyon
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
