# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://trystant.github.io
title: Mark Nyon
email: mark@grandkru.com
author: Mark Nyon
description: > # "Basic landing page for GitHub repositories & resources."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/scorintha
  - title: github
    url: https://github.com/trystant
  - title: linkedin
    url: https://www.linkedin.com/in/marknyon
